admin-console/src/main/java/com/agiletec/apsadmin/admin/package_en.properties
admin-console/src/main/java/com/agiletec/apsadmin/admin/package_it.properties
admin-console/src/main/java/org/entando/entando/apsadmin/common/UserAvatarAction.java
admin-console/src/main/resources/spring/apsadmin/commonConfig.xml
admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/admin/configSystemParams.jsp
engine/src/main/java/com/agiletec/aps/system/SystemConstants.java
engine/src/main/resources/sql/entandoPort_data_production.sql

This pull request add new configuration parameter that allow to enable/disable (into the Administration Area) the gravatar integration

Gravatar configuration

---

engine/src/main/resources/sql/plugins/jacms/port_data_production.sql

I corrected the **search_result** widget GUI by placing a check in case the **search** parameter is null

Corrected search_result widget in case of no search parameter

---

admin-console/src/main/java/com/agiletec/plugins/jacms/apsadmin/content/ContentFinderAction.java
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/contentFinding.jsp

Added a new hookpoint 'jacms.contentFinding.allContents.actions' for global actions in content list

Added hookpoint for global actions in content list

---

admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/contentFinding.jsp

Fixed 'active' class in selected checkbox
Changed deprecated content.descr in content.description

Added fixes in contentFinding.jsp

---

.gitignore
engine/pom.xml
engine/src/main/java/com/agiletec/aps/system/common/entity/model/attribute/util/NumberAttributeValidationRules.java
engine/src/main/java/com/agiletec/plugins/jacms/aps/tags/ContentListFilterTag.java
engine/src/main/java/com/agiletec/plugins/jacms/aps/tags/ContentListUserFilterOptionTag.java
engine/src/main/java/org/entando/entando/aps/system/services/storage/StorageManagerUtil.java

This evening I've took a quick look at the main project (engine) and I've spotted some issues, there are more potential issues and bugs inside the codebase, if you want we can discuss more Thursday during our meeting ...

Fix some subtle bugs caused by dangerous practices 

---

admin-console/src/main/java/com/agiletec/apsadmin/global-messages_en.properties
admin-console/src/main/java/com/agiletec/apsadmin/global-messages_it.properties
admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/common/tiles-inserts/menu.jsp

Into the admin-console menu.jsp there isn't the translation s:text of "Template"

fix issue 1 template label into menu.jsp

---

admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/common/treeBuilderPages.jsp
admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/portal/pageTree.jsp

I added a control on page status

release_4.3: updating tree pages

---

admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/common/treeBuilder-request-linksPages.jsp
admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/common/treeBuilderPages.jsp
admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/portal/pageTree.jsp
admin-console/src/main/webapp/resources/administration/css/entando-admin-console-default-theme.css

updating page tree on request, small refactor on main page tree

release_4.3: updating page tree on request

---

admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/common/layouts/default.jsp
admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/common/tiles-inserts/menu.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/common/layouts/assets-more/content_entryModel.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/common/layouts/assets-more/inc/attributeType-json-Model.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/common/layouts/assets-more/resource.jsp

Release 4.3

---

admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/portal/widget-entry.jsp
admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/portal/widget-list.jsp

adding help tooltip on widget new/edit page. Adding top help button

release_4.3: adding help tooltip on widget new/edit page. Adding top help button

---

admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/portal/specialwidget/configSimpleParameter.jsp
admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/portal/specialwidget/navigatorConfig.jsp
admin-console/src/main/webapp/resources/administration/css/entando-admin-console-default-theme.css

Widget configuration page layout updated for Navigation - Bar, Navigation - Vertical Menu, Internal Servlet widgets. Main admin console CSS file updated.

enqt-98 widget configuration page layout

---

admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/portal/include/frameInfo.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/portal/specialwidget/contentListViewer/configContentListViewer.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/portal/specialwidget/contentListViewer/entryFilter.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/portal/specialwidget/contentViewer/configContentViewer.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/portal/specialwidget/contentViewer/contentFinding.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/portal/specialwidget/rowContentViewer/chooseContentModel.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/portal/specialwidget/rowContentViewer/configRowContentListViewer.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/portal/specialwidget/rowContentViewer/contentFinding.jsp
admin-console/src/main/webapp/resources/administration/css/entando-admin-console-default-theme.css

Widget configuration page layout updated for:
- Contents - Publish Contents
- Contents - Publish a Content
- Contents - Publish a List of Contents

Enqt 98 widget conf page

---

admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/common/inc/pager_formTable.jsp
admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/common/treeBuilderCategories.jsp
admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/portal/include/frameInfo.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/common/layouts/assets-more/content_contentFinding.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/bulk/category/category-choice.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/bulk/inc/inc_contentSummary.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/contentFinding.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/contentFinding_categoryBlock.jsp
admin-console/src/main/webapp/resources/administration/css/entando-admin-console-default-theme.css

Update Content List table layout, category tree filter, table list pager, content list toolbar.

Enqt 110 content list page

---

admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/common/treeBuilder-request-categories.jsp
admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/common/treeBuilderCategories.jsp
admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/common/treeBuilderCategoriesJoin.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/common/layouts/assets-more/content.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/common/layouts/assets-more/content/bulk_categories.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/common/layouts/assets-more/content_contentFinding.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/bulk/category/category-choice.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/contentFinding_categoryBlock.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/entryContent_categoryBlock.jsp
admin-console/src/main/webapp/resources/administration/css/entando-admin-console-default-theme.css

Update category tree builder inclusion, jsp, JS, CSS, for classic and request version.

Update Category Tree common jsp

---

admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/entity/modules/monotextAttribute.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jacms-tiles.xml
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/common/layouts/assets-more/pageTree.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/entryContent.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/modules/attachAttribute.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/modules/compositeAttribute.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/modules/imageAttribute.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/modules/include/chooseResourceSubmit.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/modules/include/linkAttribute/chooseLink-menu.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/modules/include/linkAttribute/configContentLinkType.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/modules/include/linkAttribute/configPageLinkType.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/modules/include/linkAttribute/configUrlLinkType.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/modules/include/linkAttribute/linkAttributeConfigIntro.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/modules/include/linkAttribute/linkAttributeConfigReminder.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/modules/include/removeResourceSubmit.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/modules/linkAttribute.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/modules/monolistAttribute.jsp
admin-console/src/main/webapp/resources/administration/css/entando-admin-console-default-theme.css

Update entryContent: page layout, content attribute layout, linkAttribute tab view, CSS

ENQT-111: Update Add/Edit content (WIP)

---

admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/common/layouts/assets-more/inc/snippet-datepicker.jsp
admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/entity/modules/include/dateAttributeInputField.jsp
admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/entity/modules/include/listAttributes/allList_addElementButton.jsp
admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/entity/modules/include/listAttributes/allList_operationModule.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/common/layouts/assets-more/content.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/entryContent-actions-jack.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/entryContent.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/include/snippet-content.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/modules/attachAttribute.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/modules/imageAttribute.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/modules/linkAttribute.jsp
admin-console/src/main/webapp/resources/administration/css/entando-admin-console-default-theme.css

Update entryContent: sticky toolbar, content description, auto save, imageAttribute, attachAttribute, monolistAttribute and listAttribute

Update add/edit content

---

admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/contentFinding.jsp

Update contentFinding: bug fix content list table view

Bug fix content list

---

admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/common/treeBuilderCategoriesJoin.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/resource/entryResource.jsp

Fixed category tree builder for asset entries

Fix category tree

---

engine/src/main/db/update/scriptPort.sql

A better migration script from 4.2 to 4.3.

set lastUpdate not null for page metadata

---

admin-console/src/main/java/com/agiletec/apsadmin/portal/PageFinderAction.java
admin-console/src/main/java/com/agiletec/apsadmin/portal/page.xml
admin-console/src/test/java/com/agiletec/plugins/jacms/apsadmin/portal/TestPageFinderAction.java
engine/src/main/java/com/agiletec/aps/system/services/page/IPageDAO.java
engine/src/main/java/com/agiletec/aps/system/services/page/IPageManager.java
engine/src/main/java/com/agiletec/aps/system/services/page/PageDAO.java
engine/src/main/java/com/agiletec/aps/system/services/page/PageManager.java

add backoffice endpoint that returns the list of the last modified pages

Enqt 72 list of pages

---

engine/src/main/java/org/entando/entando/aps/system/init/DatabaseDumper.java

Improvement of method dumpTableData of class DatabaseDumper - finalization of dump file after resource release

ENQT-130: Fix Bug on database backup

---

admin-console/src/main/java/com/agiletec/apsadmin/portal/PageFinderAction.java
admin-console/src/main/java/com/agiletec/apsadmin/portal/page.xml
admin-console/src/main/java/com/agiletec/plugins/jacms/apsadmin/content/ContentFinderAction.java
admin-console/src/main/java/com/agiletec/plugins/jacms/apsadmin/content/content.xml
admin-console/src/main/java/org/entando/entando/plugins/jacms/apsadmin/content/rs/model/ContentJO.java
admin-console/src/main/java/org/entando/entando/plugins/jacms/apsadmin/content/rs/model/ContentsStatusResponse.java
engine/src/main/java/com/agiletec/aps/system/services/page/IPageManager.java
engine/src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/ContentDAO.java
engine/src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/ContentManager.java
engine/src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/ContentsStatus.java
engine/src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/IContentDAO.java
engine/src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/IContentManager.java

add endpoints for contents in dashboard
add some refactor

Enqt 70 status of contents

---

engine/pom.xml
engine/src/main/java/org/entando/entando/aps/system/init/DatabaseRestorer.java
engine/src/main/java/org/entando/entando/aps/system/init/util/TableDataUtils.java
engine/src/test/java/com/agiletec/aps/AllTests.java
engine/src/test/java/org/entando/entando/aps/system/init/util/TestQueryExtractor.java
engine/src/test/java/org/entando/entando/aps/system/init/util/guifragment.sql

The bug was resolved replacing a wrong processing in DatabaseRestorer class with a call to a method of class QueryExtractor

ENQT-133: Fix Bug on restore database backup 

---

admin-console/src/test/java/com/agiletec/apsadmin/portal/TestPageTreeAction.java

fix MoveTreeSuccess test

---

admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/modules/include/hypertextAttribute/type-1.jsp

Update hypertext attribute link: url link

Update hypertext attribute link: url link

---

admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/common/layouts/assets-more/inc/snippet-pageTree.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/modules/include/hypertextAttribute/entando-link.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/modules/include/hypertextAttribute/type-2.jsp

Update hypertext attribute link: page link

Update hypertext attribute link: page link

---

admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/modules/include/hypertextAttribute/type-3.jsp

Update hypertext attribute link: content link

Update hypertext attribute link: content link

---

admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/modules/include/hypertextAttribute/type-1.jsp

Update hypertext attribute link: url link form layout

Update hypertext attribute link: url link form layout

---

admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/modules/include/hypertextAttribute/type-5.jsp

Update hypertext attribute link: url resource

Update hypertext attribute link: url resource

---

admin-console/src/main/webapp/resources/administration/css/entando-admin-console-default-theme.css
admin-console/src/main/webapp/resources/administration/js/entando.grid-generator.js

Top Frame label created

---

admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/common/inc/profile-formFields.jsp

@eugeniosant @DMinnai can you guys give a look please?

ENQT-220 fix profile form fields

---

admin-console/src/main/webapp/resources/administration/js/entando.grid-generator.js

Bug fix: Top frame label on page grid

Bug fix: Top frame label on page grid

---

admin-console/src/main/java/com/agiletec/apsadmin/portal/PageTreeMenuAction.java
admin-console/src/main/java/com/agiletec/apsadmin/portal/page.xml

fix configure page action when a virtual root is present.

fix configure page action with virtual root

---

admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/portal/guifragment/guiFragment-list.jsp

Card ENQT-336 - fragments - sistemare dimensione colonna action

ENQT-335 - UX Patterns - FE - IT/EN - bug grafici

---

admin-console/src/main/java/com/agiletec/apsadmin/portal/package_en.properties
admin-console/src/main/java/com/agiletec/apsadmin/portal/package_it.properties
admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/common/layouts/assets-more/portal/pageTreeMenu-extra.jsp
admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/portal/pageTreeMenu.jsp
admin-console/src/main/webapp/resources/administration/css/pages/pageTreeMenu.css
admin-console/src/main/webapp/resources/administration/js/pages/pageTreeMenu.js

Issue: http://jira.entando.org/browse/ENQT-328
- Moved the Preview button on the right
- Moved Apply default widget button in the second row and styled
- Added visual logic to indicate if the default widgets are applied
- Created a Page on the fly dropdown on the second row, on the right
- Created initialization logic for the dropdown
- Added Page on the fly = NO logic

enqt-328 apply default widget and on the fly publishing

---

admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/common/treeBuilder.jsp

bug fix, treeBuilder check root node

bug fix, treeBuilder check root node

---

admin-console/src/main/java/com/agiletec/apsadmin/global-messages_en.properties
admin-console/src/main/java/com/agiletec/apsadmin/portal/package_it.properties
admin-console/src/main/java/com/agiletec/plugins/jacms/apsadmin/content/package_it.properties
admin-console/src/main/java/org/entando/entando/apsadmin/user/package_it.properties

label fixed

---

admin-console/src/main/java/com/agiletec/plugins/jacms/apsadmin/portal/specialwidget/viewer/ContentFinderViewerAction.java

it was working on the online version instead of draft version

fix publish single content on draft page

---

admin-console/src/main/webapp/resources/administration/js/entando.grid-generator.js

bug fix page tree grid, undefined frame position

bug fix page tree grid, undefined frame position

---

admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/category/categoryDetails.jsp
admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/category/categorySettings.jsp
admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/category/entryCategory.jsp
admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/category/include/categoryInfo_details.jsp
admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/common/treeBuilder-request-links.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/category/categoryReferences-jack.jsp

Update layout template, code refactor, bug fix categoryTree

Update Settings - Category

---

admin-console/src/main/java/com/agiletec/apsadmin/global-messages_en.properties

fix label integrazions in Integrations

fixed label Integrazions

---

admin-console/src/main/java/com/agiletec/plugins/jacms/apsadmin/resource/ResourceAction.java
admin-console/src/main/java/com/agiletec/plugins/jacms/apsadmin/resource/resource.xml
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jacms-tiles.xml
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/resource/detailResource.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/resource/entryResource.jsp

join categories, cotent references

bug fix resources

---

admin-console/src/main/java/org/entando/entando/apsadmin/system/validator/URLValidator.java
admin-console/src/main/resources/validators.xml

* add java class URLValidator.java
* add config xml validators.xml

ENQT-399 Url Validator di Struts2

---

admin-console/src/main/java/org/entando/entando/apsadmin/portal/model/package_en.properties
admin-console/src/main/java/org/entando/entando/apsadmin/portal/model/package_it.properties

Add label label.configuration

---

admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/common/layouts/default.jsp

fix backoffice encoding issue

---

pom.xml

update entando version to v4.3.2-SNAPSHOT

fix version

---

engine/src/main/java/org/entando/entando/aps/system/services/i18n/inlinediting/ApiI18nLabelInterface.java
engine/src/main/java/org/entando/entando/aps/system/services/i18n/inlinediting/model/JAXBI18nLabel.java
engine/src/main/java/org/entando/entando/plugins/jacms/aps/system/services/api/ApiContentInterface.java
engine/src/main/java/org/entando/entando/plugins/jacms/aps/system/services/api/model/JAXBContentAttribute.java
engine/src/main/resources/api/aps/apiMethods.xml
engine/src/main/resources/api/plugins/jacms/aps/apiMethods.xml
engine/src/main/resources/spring/aps/managers/baseManagersConfig.xml
engine/src/main/resources/spring/plugins/jacms/aps/managers/cmsManagersConfig.xml

add inline editing features for i18n and contents

Inline editing

---

engine/src/main/java/com/agiletec/aps/system/services/lang/ISO_639 -1_langs.xml

EN-26 - CN - Simplified and Traditional Chinese language options

---

admin-console/src/main/webapp/resources/administration/css/pages/pageTreeMenu.css

Card EN-61 CN - Highlight the page model Frame when dragging a widget over it

EN-61 CN - Highlight the page model Frame when dragging a widget over it

---

admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/common/layouts/assets-more/content_entryModel.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/model/entryModel.jsp

CN - Inline Editing tooltip improvements

CN - Inline Editing tooltip improvements

---

admin-console/src/main/java/com/agiletec/apsadmin/global-messages_it.properties
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/common/layouts/assets-more/content_entryModel.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/model/entryModel.jsp

Fix labels

---

admin-console/src/main/java/com/agiletec/apsadmin/global-messages_en.properties
admin-console/src/main/java/com/agiletec/apsadmin/global-messages_it.properties
admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/portal/model/include/pageModel-references.jsp

aggiungere i tag per indicare draft e online Fixes #222 Closes#222

---

engine/src/main/java/org/entando/entando/aps/system/services/dataobjectmodel/DataObjectModelDAO.java
engine/src/main/java/org/entando/entando/aps/system/services/dataobjectrenderer/BaseDataObjectRenderer.java
engine/src/test/java/org/entando/entando/aps/system/services/dataobjectdispender/TestDataObjectDispenser.java
engine/src/test/resources/sql/entandoServ_data_test.sql

Data ux manager update

---

admin-console/src/main/java/com/agiletec/plugins/jacms/apsadmin/content/attribute/action/hypertext/PageLinkAttributeAction.java
admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/common/treeBuilder-request-submits.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/bulk/category/category-confirm.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/modules/include/hypertextAttribute/type-2.jsp

content link ckeditor #223 Fixes #223 Close #223

content link ckeditor #223

---

admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/portal/entryPage.jsp

Reverts entando/entando-core#256

Revert "reserved page fix"

---

admin-console/src/main/webapp/resources/administration/js/pages/pageTreeMenu.js

fix Impossible widget placement

---

admin-console/pom.xml

Modified POM file to add TXT files in produced JARs, fixes KIEBPM plugin

admin-console: added TXT files in produced JAR

---

engine/src/main/java/org/entando/entando/aps/system/services/cache/CacheInfoManager.java

replaced abstract class reference with interface

Update cache info manager

---

admin-console/src/main/java/com/agiletec/apsadmin/category/CategoryAction.java
engine/src/main/java/com/agiletec/aps/system/common/AbstractCacheWrapper.java
engine/src/main/java/com/agiletec/aps/system/services/category/Category.java
engine/src/main/java/com/agiletec/aps/system/services/category/CategoryManager.java
engine/src/main/java/com/agiletec/aps/system/services/category/ICategoryManager.java
engine/src/main/java/com/agiletec/aps/system/services/category/cache/CategoryManagerCacheWrapper.java
engine/src/main/java/com/agiletec/aps/system/services/category/cache/ICategoryManagerCacheWrapper.java
engine/src/main/java/com/agiletec/aps/system/services/page/cache/PageManagerCacheWrapper.java
engine/src/main/java/com/agiletec/aps/system/services/pagemodel/cache/PageModelManagerCacheWrapper.java
engine/src/main/java/org/entando/entando/aps/system/services/widgettype/cache/WidgetTypeManagerCacheWrapper.java
engine/src/main/resources/spring/aps/managers/baseManagersConfig.xml

Upgrade category management (with cache wrapper) to facilitate insert of a DataGrid layer (realized by Infinispan connector into components project).

Upgrade category management services

---

engine/src/main/java/com/agiletec/aps/system/services/baseconfig/BaseConfigManager.java
engine/src/main/java/com/agiletec/aps/system/services/baseconfig/cache/ConfigManagerCacheWrapper.java
engine/src/main/java/com/agiletec/aps/system/services/baseconfig/cache/IConfigManagerCacheWrapper.java
engine/src/main/resources/spring/aps/managers/baseManagersConfig.xml

Upgrade configuration manager (with cache wrapper) to facilitate insert of a DataGrid layer (realized by Infinispan connector into components project).

Upgrade configuration manager

---

engine/src/main/java/com/agiletec/aps/system/services/baseconfig/cache/ConfigManagerCacheWrapper.java
engine/src/main/java/com/agiletec/aps/system/services/role/IRoleDAO.java
engine/src/main/java/com/agiletec/aps/system/services/role/RoleManager.java
engine/src/main/java/com/agiletec/aps/system/services/role/cache/IRoleManagerCacheWrapper.java
engine/src/main/java/com/agiletec/aps/system/services/role/cache/RoleManagerCacheWrapper.java
engine/src/main/resources/spring/aps/managers/baseManagersConfig.xml

Upgrade of user role manager (with cache wrapper) to facilitate insert of a DataGrid layer (realized by Infinispan connector into components project).

Upgrade role manager

---

engine/src/main/java/com/agiletec/aps/system/services/group/GroupManager.java
engine/src/main/java/com/agiletec/aps/system/services/group/IGroupDAO.java
engine/src/main/java/com/agiletec/aps/system/services/group/cache/GroupManagerCacheWrapper.java
engine/src/main/java/com/agiletec/aps/system/services/group/cache/IGroupManagerCacheWrapper.java
engine/src/main/resources/spring/aps/managers/baseManagersConfig.xml
engine/src/test/java/com/agiletec/aps/system/services/group/TestGroupManager.java

Upgrade of group manager (with cache wrapper) to facilitate insert of a DataGrid layer (realized by Infinispan connector into components project).

Upgrade group manager

---

engine/src/main/java/com/agiletec/aps/system/services/group/cache/GroupManagerCacheWrapper.java
engine/src/main/java/com/agiletec/aps/system/services/lang/cache/LangManagerCacheWrapper.java
engine/src/main/java/com/agiletec/aps/system/services/role/cache/RoleManagerCacheWrapper.java

as implemented in `I18nManagerCacheWrapper` now update a null entry raises an exception

raise exception on update null entry

---

engine/src/main/java/org/entando/entando/web/group/GroupController.java
engine/src/main/java/org/entando/entando/web/group/validator/GroupValidator.java
engine/src/main/resources/rest/messages.properties
engine/src/test/java/org/entando/entando/web/group/GroupControllerTest.java

fix mismatch code/name

---

engine/pom.xml
engine/src/main/java/com/agiletec/aps/system/services/baseconfig/BaseConfigManager.java
engine/src/main/java/com/agiletec/aps/util/ApsWebApplicationUtils.java
engine/src/main/java/org/entando/entando/web/system/ReloadConfigurationController.java
engine/src/main/resources/spring/web/servlet-context.xml
engine/src/test/java/com/agiletec/ConfigTestUtils.java
engine/src/test/java/com/agiletec/aps/ControllersAllTests.java
engine/src/test/java/org/entando/entando/TestEntandoJndiUtils.java
engine/src/test/java/org/entando/entando/web/AbstractControllerIntegrationTest.java
engine/src/test/java/org/entando/entando/web/system/ReloadConfigurationControllerTest.java
engine/src/test/resources/spring/testpropertyPlaceholder.xml

- add reload configuration controller
- setup integration tests for rest controllers
- update jndi resource setup for tests
- update junit version to 4.12

En 870 reload configuration

---

engine/src/main/java/org/entando/entando/aps/system/services/pagemodel/PageModelService.java
engine/src/main/java/org/entando/entando/web/pagemodel/validator/PageModelValidator.java

update errcode and refactor

---

engine/src/main/java/org/entando/entando/aps/system/services/widgettype/WidgetService.java
engine/src/main/java/org/entando/entando/web/common/model/Filter.java
engine/src/main/java/org/entando/entando/web/common/model/PagedMetadata.java
engine/src/main/java/org/entando/entando/web/widget/validator/WidgetValidator.java
engine/src/main/resources/rest/messages.properties

Improve validation into Widget DELETE and fix null filters element into the metadata in payload

En 1099 fix

---

engine/src/main/java/com/agiletec/plugins/jacms/aps/system/services/contentmodel/ContentModelService.java
engine/src/main/java/com/agiletec/plugins/jacms/aps/system/services/contentmodel/IContentModelService.java
engine/src/main/java/com/agiletec/plugins/jacms/aps/system/services/contentmodel/dictionary/ContentModelDictionary.java
engine/src/main/java/com/agiletec/plugins/jacms/aps/system/services/contentmodel/dictionary/ContentModelDictionaryProvider.java
engine/src/main/java/com/agiletec/plugins/jacms/aps/system/services/contentmodel/model/ContentModelDto.java
engine/src/main/java/com/agiletec/plugins/jacms/aps/system/services/contentmodel/utils/ContentModelUtils.java
engine/src/main/java/org/entando/entando/aps/system/services/role/RoleService.java
engine/src/main/java/org/entando/entando/web/plugins/jacms/contentmodel/ContentModelController.java
engine/src/main/java/org/entando/entando/web/plugins/jacms/contentmodel/model/ContentModelRequest.java
engine/src/main/java/org/entando/entando/web/plugins/jacms/contentmodel/validator/ContentModelValidator.java
engine/src/main/java/org/entando/entando/web/role/RoleController.java
engine/src/main/resources/rest/messages.properties
engine/src/main/resources/spring/plugins/jacms/aps/cms-contentmodel-dictionary-config.xml
engine/src/main/resources/spring/plugins/jacms/aps/cms-servicesConfig.xml
engine/src/test/java/com/agiletec/aps/ControllersAllTests.java
engine/src/test/java/org/entando/entando/web/page/PageConfigurationControllerIntegrationTest.java
engine/src/test/java/org/entando/entando/web/plugins/jacms/contentmodel/ContentModelControllerIntegrationTest.java
engine/src/test/java/org/entando/entando/web/plugins/jacms/contentmodel/ContentModelControllerUnitTest.java

api: add contentmodel endpoints and intellisense support

En 995 intellisense support contentmodel

---

engine/src/main/java/org/entando/entando/aps/system/services/guifragment/GuiFragmentService.java
engine/src/main/java/org/entando/entando/aps/system/services/guifragment/IGuiFragmentService.java
engine/src/main/java/org/entando/entando/web/guifragment/GuiFragmentController.java
engine/src/test/java/org/entando/entando/web/guifragment/GuiFragmentSettingsControllerIntegrationTest.java

add `/fragments/info/plugins endpoint`

add /fragments/info/plugins endpoint

---

engine/src/main/java/org/entando/entando/aps/system/services/page/IPageService.java
engine/src/main/java/org/entando/entando/aps/system/services/page/PageService.java
engine/src/main/java/org/entando/entando/web/page/PageController.java
engine/src/test/java/org/entando/entando/web/page/PageControllerIntegrationTest.java

add endpoint `/pages/search/group/free`
Similar to the standard search feature

add free pages endpoint

---

engine/src/main/java/com/agiletec/aps/system/services/page/IPageManager.java
engine/src/main/java/com/agiletec/aps/system/services/page/PageManager.java
engine/src/main/java/org/entando/entando/aps/system/services/page/IPageService.java
engine/src/main/java/org/entando/entando/aps/system/services/page/PageService.java
engine/src/main/java/org/entando/entando/aps/system/services/page/model/PageDto.java
engine/src/main/java/org/entando/entando/web/page/PageController.java
engine/src/test/java/org/entando/entando/web/page/PageControllerIntegrationTest.java

add search for online pages only

Freepages search

---

engine/src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/ContentService.java
engine/src/main/java/org/entando/entando/aps/system/services/page/IPageService.java
engine/src/main/java/org/entando/entando/aps/system/services/page/PageService.java
engine/src/main/java/org/entando/entando/aps/system/services/page/PageServiceUtilizer.java
engine/src/main/java/org/entando/entando/aps/system/services/page/model/PageDto.java
engine/src/main/java/org/entando/entando/web/page/PageController.java
engine/src/test/java/org/entando/entando/web/page/PageControllerIntegrationTest.java

- `/pages/{pageCode}`  `GET` now returns and array of `references`
-add `/pages/{code}/references/{manager}` `GET` endpoint

add entpoint /pages/{code}/references/{manager}

---

engine/src/main/java/org/entando/entando/aps/system/services/dataobject/DataObjectService.java
engine/src/main/java/org/entando/entando/aps/system/services/dataobject/IDataObjectService.java
engine/src/main/java/org/entando/entando/aps/system/services/entity/AbstractEntityTypeService.java
engine/src/main/java/org/entando/entando/aps/system/services/entity/model/EntityTypesStatusDto.java
engine/src/main/java/org/entando/entando/aps/system/services/userprofile/IUserProfileTypeService.java
engine/src/main/java/org/entando/entando/aps/system/services/userprofile/UserProfileTypeService.java
engine/src/main/java/org/entando/entando/web/dataobject/DataTypeController.java
engine/src/main/java/org/entando/entando/web/dataobject/model/DataTypeRefreshRequest.java
engine/src/main/java/org/entando/entando/web/userprofile/ProfileTypeController.java
engine/src/main/java/org/entando/entando/web/userprofile/model/ProfileTypeRefreshRequest.java
engine/src/test/java/org/entando/entando/web/dataobject/DataTypeControllerIntegrationTest.java
engine/src/test/java/org/entando/entando/web/userprofile/ProfileTypeControllerIntegrationTest.java

Upgraded also profileType refresh endpoints

En 1499 En 1500 upgrade dataType refresh endpoints

---

engine/src/main/java/org/entando/entando/web/dataobjectmodel/validator/DataObjectModelValidator.java
engine/src/test/java/org/entando/entando/web/dataobjectmodel/DataObjectModelControllerIntegrationTest.java

removed check on data type code in PUT invocation

EN-1643 fix data model validation

---

admin-console/pom.xml
pom.xml
portal-ui/pom.xml

Added plugin to upload sources jars to maven

En 1752 sources jars

---

admin-console/src/main/java/com/agiletec/plugins/jacms/apsadmin/content/IntroNewContentAction.java

Hey @joewhite101  @eugeniosant ,
Default date set to current date for new contents.
Thanks!

[4.3.4] EN-1852-434-set-default-date-to-current-date

---

admin-console/pom.xml
admin-console/src/main/java/com/agiletec/plugins/jacms/apsadmin/resource/MultipleResourceAction.java
admin-console/src/main/java/com/agiletec/plugins/jacms/apsadmin/resource/ResourceAction.java
admin-console/src/main/java/com/agiletec/plugins/jacms/apsadmin/resource/package_en.properties
admin-console/src/main/java/com/agiletec/plugins/jacms/apsadmin/resource/package_it.properties
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/resource/entryResource.jsp
engine/pom.xml
engine/src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/ResourceManager.java
engine/src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/model/AbstractMultiInstanceResource.java
engine/src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/model/AbstractResource.java
engine/src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/model/AttachResource.java
engine/src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/model/BaseResourceDataBean.java
engine/src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/model/ImageResource.java
engine/src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/model/ResourceDataBean.java
engine/src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/model/ResourceInterface.java
engine/src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/parse/ResourceDOM.java
engine/src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/parse/ResourceHandler.java
engine/src/main/java/org/entando/entando/aps/system/init/util/ApsDerbyEmbeddedDatabaseType.java
engine/src/main/resources/spring/plugins/jacms/aps/managers/resourceTypesDef.xml
engine/src/test/java/com/agiletec/plugins/jacms/aps/system/services/resource/ResourceManagerIntegrationTest.java
engine/src/test/java/com/agiletec/plugins/jacms/aps/system/services/resource/mock/MockResourceDataBean.java
src/test/config/conf/systemParams.properties

read and save metadata on images in multiple uploader added.
It should be merged a the same time with the entando-component PR below:
https://github.com/entando/entando-components/pull/300
Thanks!

[4.3.4] EN-1857-434-read-and-save-metadata-on-images-in-multiple-uploader

---

admin-console/src/main/java/com/agiletec/apsadmin/portal/PageAction.java
admin-console/src/main/java/com/agiletec/plugins/jacms/apsadmin/content/ContentAction.java
admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/portal/entryPage.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/entryContent.jsp
admin-console/src/test/java/com/agiletec/plugins/jacms/apsadmin/content/TestContentAction.java

Adding group multiselect to the 4.3.4 branch for EN-1747

EN-1747 Setting up group multiselect for 4.3.4

---

engine/src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/parse/ResourceDOM.java

metadata with special character fix added.
Could you please review this PR?
thanks!

[4.3.4] EN-1918-special-characters-metadata

---

admin-console/src/main/webapp/resources/administration/js/ckeditor/plugins/entandolink/plugin.js

Ckeditor label unlink fixed.
Could you please have a look? 
Thanks!

[4.3.4] EN-1922-434-ckeditor-unlink-label-undefined

---

engine/src/main/resources/sql/plugins/jacms/port_data_production.sql

Content preview labels fixed.
Could you please review this PR?
Thanks!

[4.3.4] EN-1923-434-not-correct-labels-in-contents-preview

---

engine/src/main/java/org/entando/entando/aps/system/init/util/ApsDerbyEmbeddedDatabaseType.java

This commit is for resource metadata task.
It should be merged a the same time with the entando-components and entando-archetypes PR below:
https://github.com/entando/entando-components/pull/304
https://github.com/entando/entando-archetypes/pull/66
Thanks!

 EN-1857-read-and-save-metadata-on-images-in-multiple-uploader

---

admin-console/src/main/webapp/resources/administration/css/entando-admin-console-default-theme.css

File buttons i18n added.
It should be merged a the same time with the entando-components PR below:
https://github.com/entando/entando-components/pull/307
Thanks !

EN-1875-CMS-contents-labels-translations 

---

admin-console/pom.xml
engine/pom.xml
pom.xml
portal-ui/pom.xml
src/test/config/conf/contextTestParams.properties

profile for sonar analysis has been created to speedup the normal development test process.

Sonar profile en 1964

---

admin-console/src/main/java/com/agiletec/apsadmin/global-messages_en.properties
admin-console/src/main/java/com/agiletec/apsadmin/global-messages_it.properties
admin-console/src/test/java/com/agiletec/apsadmin/AllTests.java
admin-console/src/test/java/com/agiletec/apsadmin/TestAdminConsoleLabelsProperties.java
admin-console/src/test/java/com/agiletec/apsadmin/TestLabelsProperties.java

Hey  @joewhite101 @eugeniosant ,
Label Fixed and tests added.
Thanks!

EN-1924-CMS-menu-contents-settings-labels

---

admin-console/src/main/java/com/agiletec/plugins/jacms/apsadmin/content/attribute/action/resource/ExtendedResourceAction.java
admin-console/src/main/java/com/agiletec/plugins/jacms/apsadmin/resource/MultipleResourceAction.java
admin-console/src/main/java/com/agiletec/plugins/jacms/apsadmin/resource/ResourceAction.java
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/resource/entryResource.jsp

Hey @joewhite101 @eugeniosant,
Resource metadata not saved from content page fixed.
Could you please review this PR?
Thanks!

[4.3.5] EN-1934-435-resource-metadata-not-saved-from-content-page

---

admin-console/src/main/java/org/entando/entando/apsadmin/filebrowser/FileBrowserAction.java
admin-console/src/main/java/org/entando/entando/apsadmin/filebrowser/package_en.properties
admin-console/src/main/java/org/entando/entando/apsadmin/filebrowser/package_it.properties
admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/filebrowser/filebrowser-upload.jsp
admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/filebrowser/include/fileUploadAddFields.jsp
admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/filebrowser/include/fileUploadFieldLabelI18n.jsp
admin-console/src/test/java/org/entando/entando/apsadmin/filebrowser/TestFileBrowserAction.java

Multiple uploader added in the file browser page.
Thanks!

[4.3.5] EN-1997-435-file-browser-multiple-upload

---

admin-console/src/main/java/com/agiletec/apsadmin/global-messages_it.properties
admin-console/src/main/java/com/agiletec/apsadmin/portal/WidgetTypeAction-validation.xml
admin-console/src/main/java/org/entando/entando/apsadmin/system/resource/CustomLocalizedTextProvider.java
admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/portal/widget-list-using.jsp
admin-console/src/test/java/com/agiletec/apsadmin/portal/TestWidgetTypeAction.java

Little refactoring of widget validation and labels

Java refactoring and labels

---

admin-console/src/main/java/org/entando/entando/apsadmin/filebrowser/FileBrowserAction.java
admin-console/src/main/java/org/entando/entando/apsadmin/filebrowser/package_en.properties
admin-console/src/main/java/org/entando/entando/apsadmin/filebrowser/package_it.properties
admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/filebrowser/filebrowser-upload.jsp
admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/filebrowser/include/fileUploadAddFields.jsp
admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/filebrowser/include/fileUploadFieldLabelI18n.jsp
admin-console/src/test/java/org/entando/entando/apsadmin/filebrowser/TestFileBrowserAction.java

file browser -> multiple upload added,
could you please review this PR?
Thanks!

EN-1997-file-browser-multiple-upload

---

admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/resource/entryResource.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/resource/fileUploadAddFields.jsp
admin-console/src/main/webapp/resources/administration/crop-editor/crop-editor.js

Fixes/Improvements:
- Better cropping UX;
- Fixed image flipping;
- Fixed stuck images; 
- Fixed toolbar inconsistencies.

En 1939 crop editor fixes

---

admin-console/src/main/webapp/resources/administration/crop-editor/crop-editor.js

Fixed Crop editor on IE 11.
https://jira.entando.org/browse/EN-2066

EN-1939 Fixing Crop editor on IE 11.

---

admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/resource/entryResource.jsp
admin-console/src/main/webapp/resources/administration/crop-editor/crop-editor.css
admin-console/src/main/webapp/resources/administration/crop-editor/crop-editor.js

Adding toast feedback on crop created.
https://jira.entando.org/browse/EN-1939
https://jira.entando.org/browse/EN-2066

EN-1939 & EN-266 Adding toast feedback on crop created.

---

admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/resource/entryResource.jsp

https://jira.entando.org/browse/EN-2066

EN-1939 & EN-266 Removing crop/move tools.

---

admin-console/src/main/java/com/agiletec/plugins/jacms/apsadmin/content/attribute/action/resource/ExtendedResourceAction.java
admin-console/src/main/java/com/agiletec/plugins/jacms/apsadmin/content/attribute/action/resource/ExtendedResourceFinderAction.java
admin-console/src/main/java/com/agiletec/plugins/jacms/apsadmin/content/attribute/action/resource/ResourceAttributeAction.java
admin-console/src/main/java/com/agiletec/plugins/jacms/apsadmin/content/attribute/action/resource/ResourceAttributeActionHelper.java
admin-console/src/main/java/com/agiletec/plugins/jacms/apsadmin/resource/MultipleResourceAction.java
admin-console/src/main/java/com/agiletec/plugins/jacms/apsadmin/resource/ResourceAction.java
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/resource/entryResource.jsp
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/resource/imageArchive.jsp

Upload to mono-list for images and attachments inside content added.
@otarza please add your FE fix here.
thanks!

List res attribu improv

---

admin-console/src/main/webapp/resources/administration/crop-editor/crop-editor.js

Fixing delete action for not-yet initialized cropper items.

EN-1939 & EN-266 fixing delete action 

---

admin-console/src/main/java/com/agiletec/plugins/jacms/apsadmin/resource/FieldError.java
admin-console/src/main/java/com/agiletec/plugins/jacms/apsadmin/resource/MultipleResourceAction.java
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/resource/entryResource.jsp
admin-console/src/main/webapp/resources/administration/crop-editor/crop-editor.css
admin-console/src/main/webapp/resources/administration/crop-editor/crop-editor.js

https://jira.entando.org/browse/EN-2128
& 
https://jira.entando.org/browse/EN-2134

EN-2128 implementation of multiple/drag and drop files uploader

---

admin-console/src/main/java/com/agiletec/apsadmin/portal/WidgetTypeAction-validation.xml

I just ported the code from master and fixed the reference to error message

EN-2113 Fixed Widget Code Length Validation

---

admin-console/src/main/java/com/agiletec/plugins/jacms/apsadmin/content/model/ContentModelAction.java
admin-console/src/main/java/com/agiletec/plugins/jacms/apsadmin/content/model/package_en.properties
admin-console/src/main/java/com/agiletec/plugins/jacms/apsadmin/content/model/package_it.properties
admin-console/src/main/resources/spring/plugins/jacms/apsadmin/content/contentModelActionsConfig.xml
admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/model/modelReferences.jsp
admin-console/src/test/java/com/agiletec/apsadmin/portal/TestWidgetsViewerAction.java
admin-console/src/test/java/com/agiletec/plugins/jacms/apsadmin/content/model/TestContentModelAction.java
engine/src/main/java/com/agiletec/plugins/jacms/aps/system/services/contentmodel/ContentModelManager.java
engine/src/main/java/com/agiletec/plugins/jacms/aps/system/services/contentmodel/ContentModelReference.java
engine/src/main/java/com/agiletec/plugins/jacms/aps/system/services/contentmodel/IContentModelManager.java
engine/src/test/java/com/agiletec/plugins/jacms/aps/system/services/contentmodel/ContentModelManagerTest.java
engine/src/test/resources/sql/plugins/jacms/port_data_test.sql

Changes of EN-2131 for versions 5.1.0 and 5.0.1 have been ported into 4.3.6

EN-1927 (4.3.6) Modified content model references detection logic

---

admin-console/src/main/java/org/entando/entando/apsadmin/dataobject/model/package_en.properties
admin-console/src/main/java/org/entando/entando/apsadmin/dataobject/model/package_it.properties
admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/datatype/ux/entryModel.jsp

https://jira.entando.org/browse/EN-2119

EN-2119 Fixed labels

---

admin-console/src/main/java/org/entando/entando/apsadmin/filebrowser/FileBrowserAction.java
admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/filebrowser/filebrowser-entryFile.jsp

https://jira.entando.org/browse/EN-2121

EN-2121 fixes broken file download in file browser [5.0.1]

---

admin-console/src/main/java/org/entando/entando/apsadmin/filebrowser/FileBrowserAction.java
admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/filebrowser/filebrowser-entryFile.jsp

https://jira.entando.org/browse/EN-2121

EN-2121 fixes broken file download in file browser [master]

---

engine/src/main/java/org/entando/entando/aps/system/init/SwaggerInitializer.java
engine/src/main/java/org/entando/entando/web/swagger/SwaggerConfig.java

I changed the grant type to password. Everything else is the same. I'll need to update the instructions to use swagger (need to use also user/password authentication with clientId/secret)

Fix for Swagger/Spring Security

---

admin-console/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/resource/entryResource.jsp
admin-console/src/main/webapp/resources/administration/crop-editor/crop-editor.js

https://jira.entando.org/browse/EN-2189

EN-2189 Fixed file upload labels.

---

admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/common/treeBuilderCategories.jsp
admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/common/treeClassicNodesState.jsp

This pull request is associated with [PR #385 in entando-components](https://github.com/entando/entando-components/pull/385).
If you want to test this changes you need to use also that changes.

EN-2132 (5.1.0) Fixed category tree behavior for classic nodes style in Content edit

---

admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/common/treeBuilderCategories.jsp
admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/common/treeClassicNodesState.jsp

This pull request is associated with [PR #386 in entando-components](https://github.com/entando/entando-components/pull/386).
If you want to test this changes you need to use also that changes.

EN-2132 (5.0.1) Fixed category tree behavior for classic nodes style in Content edit

---

admin-console/src/main/java/com/agiletec/apsadmin/portal/package_en.properties
admin-console/src/main/java/com/agiletec/apsadmin/portal/package_it.properties
admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/portal/pageSearchResult.jsp

changed label from Full Title to Full Path

---

admin-console/src/main/java/com/agiletec/apsadmin/portal/package_en.properties
admin-console/src/main/java/com/agiletec/apsadmin/portal/package_it.properties
admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/portal/pageSearchResult.jsp

changing label from Full Title to Full Path

---

engine/src/main/java/org/entando/entando/aps/servlet/security/OAuth2SecurityConfiguration.java

disabled X-Frame-Options response header in Spring Security

Upgrade of WebSecurityAdapter

---

admin-console/src/main/java/com/agiletec/apsadmin/system/entity/package_en.properties
admin-console/src/main/java/com/agiletec/apsadmin/system/entity/package_it.properties

data type entry labels for tooltip added

adding missing info strings for data type entry form tooltips

---

admin-console/src/main/java/com/agiletec/apsadmin/system/entity/package_en.properties
admin-console/src/main/java/com/agiletec/apsadmin/system/entity/package_it.properties

data type entry labels for tooltip added

adding missing info strings for data type entry tooltips

---

engine/pom.xml
engine/src/main/java/org/entando/entando/aps/system/init/SwaggerInitializer.java
engine/src/main/java/org/entando/entando/web/swagger/SwaggerConfig.java

Fix for both Guava dependency clash with CMS and also to make Swagger work with Spring Security

EN-2178 Fix for Swagger

---

admin-console/src/main/java/org/entando/entando/apsadmin/system/resource/CustomLocalizedTextProvider.java
admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/portal/widget-list-using.jsp
admin-console/src/test/java/com/agiletec/apsadmin/portal/TestWidgetTypeAction.java

Fixed CustomLocalizedProvider - Added option for properties into war (Jboss/Wildfly)
EN-1840 fix label in widget info
EN-1799 Add test for validation of widget type code length

Added missing improvements

---

engine/src/main/java/com/agiletec/aps/system/services/user/AbstractUser.java

Fixed a call of the method getRefreshToken to itself to avoid stack trace blowing up if someone calls it.
I also tidyied it up a bit fixing field names and other minor things.

Fixed infinite loop in getRefreshToken method

---

engine/src/main/java/org/entando/entando/aps/system/services/storage/StorageManagerUtil.java

Removed duplicated condition in endWithParentDir method and some tidy up

---

admin-console/src/test/java/org/entando/entando/apsadmin/common/TestActivityStream.java
admin-console/src/test/java/org/entando/entando/apsadmin/filebrowser/TestFileBrowserAction.java
engine/src/main/java/com/agiletec/aps/system/services/i18n/I18nManager.java
engine/src/main/java/com/agiletec/aps/system/services/i18n/wrapper/I18nLabelBuilder.java
engine/src/main/java/org/entando/entando/aps/system/services/page/PageTokenManager.java
engine/src/main/java/org/entando/entando/aps/system/services/storage/LocalStorageManager.java
engine/src/main/java/org/entando/entando/aps/system/services/storage/api/LocalStorageManagerInterface.java
engine/src/main/java/org/entando/entando/web/swagger/SwaggerMvcAdapter.java
engine/src/test/java/com/agiletec/aps/system/services/page/PageTestUtil.java
engine/src/test/java/com/agiletec/aps/system/services/user/UserManagerTest.java
engine/src/test/java/org/entando/entando/aps/system/services/cache/CacheInfoManagerTest.java
engine/src/test/java/org/entando/entando/aps/system/services/dataobjectmapper/DataObjectMapperManagerTest.java
engine/src/test/java/org/entando/entando/aps/system/services/dataobjectmapper/cache/DataObjectMapperCacheWrapperTest.java
engine/src/test/java/org/entando/entando/aps/system/services/entity/EntityManagerServiceTest.java

Updated some deprecated classes

---

engine/src/main/java/org/entando/entando/aps/system/services/entity/AbstractEntityTypeService.java
engine/src/main/java/org/entando/entando/aps/system/services/entity/model/EntityTypeShortDto.java
engine/src/test/java/org/entando/entando/aps/system/services/entity/AbstractEntityTypeServiceTest.java
pom.xml

While I was testing for EN-2162, I found a filter that wasn't working. I added a test and fixed it.

Fixed filtering that wasn't working properly

---

engine/src/main/java/org/entando/entando/web/common/interceptor/EntandoOauth2Interceptor.java

consider RequestMapping annotation aliases such as GetMapping, PostMapping, PutMapping...

EN-2277 Changed annotation check to 

---

admin-console/src/main/java/com/agiletec/apsadmin/user/group/GroupAction.java
admin-console/src/main/java/com/agiletec/apsadmin/user/role/RoleAction.java
admin-console/src/main/java/org/entando/entando/apsadmin/user/UserAction.java
admin-console/src/main/java/org/entando/entando/apsadmin/user/UserAuthorizationAction.java
admin-console/src/test/java/com/agiletec/apsadmin/system/entity/TestEntityManagersAction.java

We had some conditions in the format 
`name.trim().length()>=0`
These are always true. I removed them and tidied up the files that I touched.
I also fixed one test that looked like it was running but it wasn't really testing anything, just failing in silence

Minor tidy up and test fix

---

engine/src/main/java/org/entando/entando/aps/system/init/DatabaseManager.java
engine/src/main/java/org/entando/entando/aps/system/init/InitializerManager.java
engine/src/main/java/org/entando/entando/aps/system/init/model/AbstractComponentModule.java
engine/src/main/java/org/entando/entando/aps/system/init/model/Component.java
engine/src/main/java/org/entando/entando/aps/system/init/model/ComponentEnvironmentImpl.java
engine/src/main/java/org/entando/entando/aps/system/init/model/ComponentModule.java

Just made some methods public, introduced two interfaces and a bit of refactoring.

EN-2312 Changes for supporting installation of a single component

---

engine/src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/widget/ContentViewerHelper.java
engine/src/main/java/com/agiletec/plugins/jacms/aps/system/services/searchengine/ISearchEngineDAOFactory.java
engine/src/main/java/com/agiletec/plugins/jacms/aps/system/services/searchengine/SearchEngineDAOFactory.java
engine/src/main/java/com/agiletec/plugins/jacms/aps/system/services/searchengine/SearchEngineManager.java

Add check of current subfolder for OpenShift env (multi pod) in Search Engine and a check for null current widget (case of "content tag" into page model or its include) into Content Viewer Helper

SUP-174 Improvement of Search Engine and Content Viewer (4.3.6)

---

engine/src/main/java/org/entando/entando/aps/system/init/DatabaseManager.java
engine/src/main/java/org/entando/entando/aps/system/init/InitializerManager.java
engine/src/main/java/org/entando/entando/aps/system/init/model/AbstractComponentModule.java
engine/src/test/java/com/agiletec/aps/AllTests.java
engine/src/test/java/org/entando/entando/aps/system/init/DatabaseManagerTest.java
engine/src/test/java/org/entando/entando/aps/system/init/util/ComponentUtils.java
engine/src/test/resources/components/test_component/component.xml

This PR is to start supporting DE components uninstall

En 2311 components uninstall

---

admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/entity/include/validation-rules-date.jsp

Adds necessary div and class to not break admin ui for Date attribute validation

Solves a minor issue with css of the AdminUI

---

engine/src/main/java/org/entando/entando/web/category/CategoryController.java
engine/src/test/java/org/entando/entando/web/category/CategoryControllerTest.java

SME-2 Changed authorization on categories API

---

engine/src/main/java/org/entando/entando/aps/system/services/label/LabelDtoBuilder.java
engine/src/main/java/org/entando/entando/aps/system/services/label/LabelRequestListProcessor.java
engine/src/main/java/org/entando/entando/aps/system/services/label/LabelService.java
engine/src/main/java/org/entando/entando/aps/system/services/label/model/LabelDto.java
engine/src/test/java/org/entando/entando/aps/system/services/label/LabelServiceTest.java

Fixing label filtering and adding test coverage.
P.S: I did not use the sort property because the old code didn't use as well, so I imagine it might break things if I do.

EN-2368 Fixing label filtering and adding test coverage.

---

engine/src/main/java/org/entando/entando/aps/system/services/activitystream/ActivityStreamService.java
engine/src/test/java/org/entando/entando/web/activitystream/ActivityStreamControllerIntegrationTest.java

EN-2369 Fixing filter by actionName

---

admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/common/login.jsp

https://jira.entando.org/browse/EN-2467

EN-2467 - Changing messages on login page.

---

pom.xml

This fixes issue with entando-de-app not running with jetty-container profile

Updates mockito version

---

engine/src/main/java/org/entando/entando/web/common/handlers/RestExceptionHandler.java
engine/src/main/resources/spring/baseSystemConfig.xml
engine/src/main/resources/spring/web/servlet-context.xml

Configured Multipart Bean Resolver to use configuration property from `systemParams.properties`

EN6-77 Configured MultipartBeanResolver to use configuration property from systemParams.properties

---

engine/src/main/resources/rest/messages.properties
engine/src/main/resources/spring/web/servlet-context.xml

i18n for endpoints for Content Settings, Digital Assets and Contents;

EN6-97 i18n for the CMS endpoints

---

engine/src/main/java/org/entando/entando/web/common/model/PagedMetadata.java
engine/src/test/java/org/entando/entando/web/common/PagedMetadataTest.java

Adding fix for lastPage value when totalItems are 0

EN6-178 Fixing lastPage values when totalItems are 0

---

engine/src/main/db/update/scriptPort.sql
engine/src/main/java/com/agiletec/aps/system/common/AbstractSearcherDAO.java
engine/src/main/java/com/agiletec/aps/system/common/FieldSearchFilter.java
engine/src/main/java/org/entando/entando/web/common/model/Filter.java

Implementing the NOT operator for filters

En6 141 advanced filtering for content

---

admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/common/login.jsp
admin-console/src/main/webapp/resources/administration/css/entando-admin-console-default-theme.css

Login page now designed for mobile/tablet size

EN6-171 login screen of admin console for mobile / tablet

---

engine/src/main/java/com/agiletec/aps/system/common/entity/model/attribute/AttributeInterface.java
engine/src/main/java/com/agiletec/aps/system/common/entity/model/attribute/BooleanAttribute.java
engine/src/main/java/com/agiletec/aps/system/common/entity/model/attribute/HypertextAttribute.java
engine/src/main/java/org/entando/entando/aps/system/services/entity/model/AttributeTypeDto.java

Due to new requirements the values for searchableOptionSupported and indexableOptionSupported needed to me changed

EN6-143 Changing attributes values to match new requirements

---

engine/src/main/java/org/entando/entando/aps/system/services/page/model/WidgetConfigurationDto.java
engine/src/main/java/org/entando/entando/aps/system/services/page/serializer/WidgetConfigPropertiesDeserializer.java
engine/src/main/java/org/entando/entando/aps/system/services/page/serializer/WidgetConfigPropertiesSerializer.java
engine/src/main/java/org/entando/entando/web/page/PageConfigurationController.java
engine/src/main/java/org/entando/entando/web/page/model/WidgetConfigurationRequest.java

EN6-183 WidgetConfig JSON Format

---

engine/src/main/java/org/entando/entando/aps/system/services/entity/model/EntityAttributeDto.java
engine/src/main/resources/rest/messages.properties

EN6-190 Fixed Create, Edit, Get and List Content with CMS Attributes

---

pom.xml

Changes included in this PR
Changes to the following files to upgrade the vulnerable dependencies to a fixed version:
pom.xml
Vulnerabilities that will be fixed
With an upgrade:
pom.xml
com.fasterxml.jackson.core:jackson-databind@2.9.9 > com.fasterxml.jackson.core:jackson-databind@2.9.10.1
Deserialization of Untrusted Data
com.fasterxml.jackson.dataformat:jackson-dataformat-xml@2.9.9 > com.fasterxml.jackson.dataformat:jackson-dataformat-xml@2.10.0
Deserialization of Untrusted Data
commons-beanutils:commons-beanutils@1.9.2 > commons-beanutils:commons-beanutils@1.9.4
Deserialization of Untrusted Data
org.apache.httpcomponents:httpclient@4.5.1 > org.apache.httpcomponents:httpclient@4.5.3
Directory Traversal

Fix Vulnerabilities

---

engine/src/main/java/org/entando/entando/aps/system/services/widgettype/model/WidgetDtoBuilder.java

hasConfig attribute should be true when configUi is not blank.

Fix hasConfig attribute

---

admin-console/src/main/java/com/agiletec/apsadmin/portal/package_it.properties
engine/src/main/java/com/agiletec/aps/system/common/entity/model/JAXBEntity.java
engine/src/main/java/org/entando/entando/aps/system/services/api/UnmarshalUtils.java
engine/src/test/java/org/entando/entando/aps/system/services/dataobject/api/TestApiDataObjectInterface.java
engine/src/test/java/org/entando/entando/aps/system/services/i18n/TestApiI18nLabelInterface.java

Fix label Aggingi servizi -> Aggiungi servizi

Fix label ITA

---

admin-console/src/main/java/org/entando/entando/apsadmin/api/package_en.properties
admin-console/src/main/java/org/entando/entando/apsadmin/api/package_it.properties
admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/api/consumer-entry.jsp
admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/portal/configPage.jsp
admin-console/src/main/webapp/WEB-INF/apsadmin/jsp/portal/widget-list-menu.jsp

This PR contains some ui improvements tested into several projects based on 5.3.0 version of entando

UI improvements

---

engine/src/test/java/org/entando/entando/web/page/PageControllerIntegrationTest.java

This is just a test to look for the problem, the API is looking fine

ENG-303 Add page, remove ir and add it again test

---

engine/src/main/java/org/entando/entando/web/common/interceptor/ActivityStreamInterceptor.java

Hey @joewhite101 @Kerruba ,
this PR remove the logging of the exception if one widget without config is drag and dropped in the page configuration.
thanks

ENG-437: Removed exception log if request body is empty

---

engine/src/main/java/org/entando/entando/aps/system/services/label/LabelService.java
engine/src/main/java/org/entando/entando/web/label/LabelController.java
engine/src/test/java/org/entando/entando/aps/system/services/label/LabelServiceTest.java

Hey @joewhite101 @Kerruba ,
this commit fix the labels pagination issue.
Could you please review this PR?
Thanks.

ENG-64: fixes label pagination

---

engine/src/main/java/org/entando/entando/aps/system/services/page/PageService.java
engine/src/main/java/org/entando/entando/web/page/PageController.java
engine/src/main/java/org/entando/entando/web/page/validator/PageValidator.java
engine/src/test/java/org/entando/entando/web/page/PageControllerIntegrationTest.java

Hey @joewhite101 @Kerruba @eugeniosant ,
With this PR the user now can change the position of a page  (updating the parent page) also in the "edit page" page.
Thanks

ENG-250: parent page update fixed in page edit

---

engine/src/main/resources/rest/messages.properties

Hey @Kerruba @joewhite101 ,
this is a new validation message used in this [cms PR](https://github.com/entando/entando-components/pull/638)
Thanks

ENG-468: added delete content template validation message 

---

engine/src/main/java/org/entando/entando/web/user/UserController.java
engine/src/main/java/org/entando/entando/web/user/validator/UserValidator.java
engine/src/main/resources/rest/messages.properties
engine/src/test/java/org/entando/entando/web/user/UserControllerUnitTest.java
engine/src/test/java/org/entando/entando/web/user/validator/UserValidatorTest.java

Hi @joewhite101 @BrenoQVDS @Kerruba @gidesan,
I added a validation to avoid a user to delete himself.
Thanks

ENG-462: Added a validation to avoid user to delete himself

---

engine/src/main/java/org/entando/entando/aps/system/services/page/PageAuthorizationService.java
engine/src/main/java/org/entando/entando/aps/system/services/page/PageService.java
engine/src/main/java/org/entando/entando/web/category/CategoryController.java
engine/src/main/java/org/entando/entando/web/group/GroupController.java
engine/src/main/java/org/entando/entando/web/language/LanguageController.java
engine/src/main/java/org/entando/entando/web/page/PageConfigurationController.java
engine/src/main/java/org/entando/entando/web/page/PageController.java
engine/src/main/java/org/entando/entando/web/pagemodel/PageModelController.java
engine/src/main/java/org/entando/entando/web/widget/WidgetController.java
engine/src/test/java/org/entando/entando/web/category/CategoryControllerIntegrationTest.java
engine/src/test/java/org/entando/entando/web/category/CategoryControllerTest.java
engine/src/test/java/org/entando/entando/web/page/PageControllerIntegrationTest.java
engine/src/test/java/org/entando/entando/web/page/PageControllerTest.java
engine/src/test/java/org/entando/entando/web/widget/WidgetControllerIntegrationTest.java
engine/src/test/java/org/entando/entando/web/widget/WidgetControllerTest.java

Fixed permissions for creating and configuring a page.

ENG-683 Page Configuration Permissions

---

admin-console/src/main/webapp/resources/administration/css/entando-admin-console-default-theme.css

ENG-731-admin-console-cms- added ellipsis for action dropdown

ENG-731-admin-console-cms- added ellipsis for action dropdown
